config/routes.rb
Rails.application.routes.draw do
  root 'users#index'
  resources :users do
    member do
      get :profile
      patch :update_profile
      get :change_password
      post :update_password
    end
  end

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/user.rb
class User < ApplicationRecord
    validate :check_password, on: :update
    validates :first_name,presence: true
    validates :password,presence: true, on: :create

    def check_password
        u = User.find_by_id(self.id)
        if self.password != u.password and self.email!=u.email
        errors.add(:base, "Password is incorrect.")
        else
        self.password=u.password
        end
    end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: %i[ show edit update destroy profile update_profile ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  def profile
  
  end
  
  def update_profile
    if @user.update(user_params)
      respond_to do |format|
        format.js
        flash.now[:alert]=["Successfully Updated"]
      end
    else 
      flash.now[:alert] = @user.errors.full_messages
      respond_to do |format|
        format.js
      end
    end
  end

  def change_password
    
  end

  def update_password
    if(@user.password==params[:password])
      @user.update_attribute(:password,params[:new_password])
      redirect_to new_users_path
    else 
      flash.now[:alert]=["Incorrect old password"]
      puts flash[:alert]
      render "change_password"
    end
  end


  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :subscription, :subscription_email)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JavascriptApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.text_field :email %>
  </div>

  <div>
    <%= form.label :password, style: "display: block" %>
    <%= form.text_field :password %>
  </div>

  <div>
    <%= form.label :subscription, style: "display: block" %>
    <%= form.check_box :subscription %>
  </div>

  <div>
    <%= form.label :subscription_email, style: "display: block" %>
    <%= form.text_field :subscription_email %>
  </div>

  <div>
  <%= form.submit data: { disable_with: "Saving..." } %>
  </div>
<% end %>

app/views/users/_user.html.erb
<div id="<%= dom_id user %>">
  <p>
    <strong>First name:</strong>
    <%= user.first_name %>
  </p>

  <p>
    <strong>Last name:</strong>
    <%= user.last_name %>
  </p>

  <p>
    <strong>Email:</strong>
    <%= user.email %>
  </p>

  <p>
    <strong>Password:</strong>
    <%= user.password %>
  </p>

  <p>
    <strong>Subscription:</strong>
    <%= user.subscription %>
  </p>

  <p>
    <strong>Subscription email:</strong>
    <%= user.subscription_email %>
  </p>

</div>

app/views/users/change_password.html.erb
<h1> Change Password</h1>
<%=flash[:alert]%>
<% if flash[:alert] %>
  <div >
    <ul>
      <% flash[:alert].each do |error| %>
        <li style="color:red;"><%= error %></li>
      <% end %>
    </ul>
  </div>
<% end %>
<%= form_with(url: users_path,url: update_password_user_path) do |form| %>
  <%= form.password_field :password, placeholder: 'enter old password' %><br/><br/>
  <%= form.password_field :new_password, placeholder: 'password' ,:id => "new_password",onchange:"check_validation();"%><br/><br/>
  <%= form.password_field :confirm_password, placeholder: 'confirm_password' ,onchange:"check_password();",:id => "confirm_password"%><br/><br/>
  <%= form.submit :id => "form_submit",style:"display:none;"%>
<% end %>

<script>
    function check_validation()
    {
        var password = document.getElementById("new_password").value;
        if(password.length <= 3 || password.length > 12)
        {
            alert("password length should be in between 3 and 12 characters")
            document.getElementById("new_password").value=""
        }
    }

    function check_password()
    {
        var password = document.getElementById("new_password").value;
        var confirm_password = document.getElementById("confirm_password").value;
        console.log(password)
        console.log(confirm_password)
        if(password)
        {
            if(confirm_password==password)
            {
                alert("password matched...")
                document.getElementById("check")
                document.getElementById("form_submit").style.display="block"
            }
            else
            {
            alert("password is not matching")
            //document.getElementById("confirm_password").value=""
            document.getElementById("form_submit").style.display="none"
            }
        }
        else
        {
            alert("please first type password")
            document.getElementById("confirm_password").value=""
        }
    }

</script>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Show this user", @user %> |
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Users</h1>

<div id="users">
  <% @users.each do |user| %>
    <%= render user %>
    <p>
      <%= link_to "Show this user", user %>
      <%= link_to "Show User Profile", profile_user_path(id: user.id) %>

    </p>
  <% end %>
</div>
<%= link_to "New user", new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render "form", user: @user %>

<br>

<div>
  <%= link_to "Back to users", users_path %>
</div>

app/views/users/profile.html.erb
<h3>User Profile</h3>
<table border='2px'>
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Email</th>
    <th>Subscription</th>
    <th>Subscription Email</th>
    
  </tr>
  <tr id='update-data'>
    <td><%= @user.first_name %></td>
    <td><%= @user.last_name %></td>
    <td><%= @user.email %></td>
    <td><%= @user.subscription %></td>
    <td><%= @user.subscription_email %></td>		
  </tr>
</table>
<br/>
<br/>
<h3>Update Profile</h3>
<%= form_with(model: @user,url: update_profile_user_path,local: false,scope: :user) do |form| %>
  <div>
    <%= form.label :first_name, style: "display: block" %>
    <%= form.text_field :first_name %>
  </div>

  <div>
    <%= form.label :last_name, style: "display: block" %>
    <%= form.text_field :last_name %>
  </div>

  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email, placeholder: 'email',onchange:"showpassword();" %><br/><br/>
    <%= form.password_field :password, placeholder: 'Please enter your password' ,:id => "password",style:"display:none;"%><br/>
  </div>

  <div>
    <%= form.label :Subscribe %>
    <%= form.check_box :subscription,:id => "check" %><br/><br/>
  </div>
  
  <div>
    <%= form.label :subscription_email, style: "display: block" %>
    <%= form.email_field :subscription_email, placeholder: 'email',:id => "email"%><br/><br/>
  </div>

  <div>
    <%= form.submit data: { disable_with: "Saving..." },:id => "form_submit" %>
  </div>

<% end %><br/>
<%= link_to "change password", change_password_user_path(id: @user.id) %><br/>

  
<script>

function showpassword()
{
  document.getElementById("password").style.display="block"
}

</script>

app/views/users/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @user %>

<div>
  <%= link_to "Edit this user", edit_user_path(@user) %> |
  <%= link_to "Back to users", users_path %>

  <%= button_to "Destroy this user", @user, method: :delete %>
</div>

app/views/users/update_profile.js.erb
$("#update-data").html('<%= escape_javascript(render('user_path', user: @user)).html_safe %>');